import {
  CONFIRM_SIGN_IN_PROVIDERS,
  CONFIRM_SIGN_UP_PROVIDERS,
  GET_USER_PROVIDERS,
  RESEND_CODE_PROVIDERS,
  RESEND_PASSWORK_PROVIDERS,
  SIGN_UP_PROVIDERS,
  SING_IN_PROVIDERS,
} from './auth';

export const DataIoc = {
  providers: [
    ...SIGN_UP_PROVIDERS,
    ...CONFIRM_SIGN_UP_PROVIDERS,
    ...GET_USER_PROVIDERS,
    ...RESEND_CODE_PROVIDERS,
    ...RESEND_PASSWORK_PROVIDERS,
    ...SING_IN_PROVIDERS,
    ...CONFIRM_SIGN_IN_PROVIDERS,
  ],
};
